// react/src/app/posts/page.tsx
"use client";
import Axios from 'axios';
import Link from 'next/link';
import { useState, useEffect } from 'react';

export default function Posts() {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    Axios.get('https://jsonplaceholder.typicode.com/posts')
      .then((res) => {
        setPosts(res.data);
      })
      .catch((err) => {
        console.error(err);
      });
  }, []);

  return (
    <div className="container mx-auto p-6">
      <h1 className="text-4xl font-semibold mb-6">Post List</h1>
      <ul className="space-y-4">
        {posts.map((post) => (
          <li key={post.id} className="border border-gray-300 rounded-lg p-4 hover:bg-gray-100 transition duration-200">
            <Link
              href={`/post/${post.id}`}
              className="text-xl font-medium text-blue-600 hover:text-blue-800 transition duration-300"
            >
              {post.title}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

// vue/src/views/Posts.vue
<template>
  <div class="container mx-auto p-6">
    <h1 class="text-4xl font-semibold mb-6 text-center">Post List</h1>
    <ul class="space-y-4">
      <li v-for="post in posts" :key="post.id" class="border border-gray-300 rounded-lg p-4 hover:bg-gray-100 transition duration-200">
        <router-link
          :to="`/post/${post.id}`"
          class="text-xl font-medium text-blue-600 hover:text-blue-800 transition duration-300"
        >
          {{ post.title }}
        </router-link>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import axios from 'axios';

const posts = ref([]);

onMounted(() => {
  axios
    .get('https://jsonplaceholder.typicode.com/posts')
    .then((response) => {
      posts.value = response.data;
    })
    .catch((error) => {
      console.error('Error fetching posts:', error);
    });
});
</script>
<style scoped>
@media (hover: hover) {
  a:hover {
    background-color: transparent;
  }
}
</style>
